apiVersion: v1
kind: ServiceAccount
metadata:
  name: klusterlet-addon-appmgr
  namespace: open-cluster-management-agent-addon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicluster-operators
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-operators
subjects:
- kind: ServiceAccount
  name: klusterlet-addon-appmgr
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: multicluster-operators
  apiGroup: rbac.authorization.k8s.io

