apiVersion: v1
kind: Service
metadata:
  labels:
    app: multicluster-operators-channel
  name: channels-apps-open-cluster-management-webhook-svc
  namespace: hypershift-clusters-acm-1
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: multicluster-operators-channel
  sessionAffinity: None
  type: ClusterIP
