# oc edit validatingwebhookconfiguration  channels.apps.open.cluster.management.webhook.validator
# set port=9443
---
apiVersion: v1
kind: Service
metadata:
  name: channels-apps-open-cluster-management-webhook-svc
  namespace: hypershift-clusters-acm-1
spec:
  ports:
  - port: 443
    protocol: TCP
  sessionAffinity: None
  type: ClusterIP
---
# 172.30.166.186  is the cluster ip for the channel pod running on the management cluster
kind: Endpoints
apiVersion: v1
metadata:
  name: channels-apps-open-cluster-management-webhook-svc
  namespace: hypershift-clusters-acm-1
subsets:
  - addresses:
      - ip: 172.30.166.186
    ports:
      - port: 443
