apiVersion: v1
kind: Namespace
metadata:
  name: test-channel-4-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: test-channel-4
  namespace: test-channel-4-ns
spec:
  pathname: https://github.com/xiangjingli/testrepo.git
  type: GitHub
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-appsub-4-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: git-gb-placement-4
  namespace: test-appsub-4-ns
spec:
  clusterSelector: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: git-gb
    subscription-pause: "false"
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: guestbook
    apps.open-cluster-management.io/reconcile-option: merge    
  name: git-gb-subscription-4
  namespace: test-appsub-4-ns
spec:
  channel: test-channel-4-ns/test-channel-4
  placement:
    placementRef:
      kind: PlacementRule
      name: git-gb-placement-4
