apiVersion: v1
kind: Namespace
metadata:
  name: ch-git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git
  namespace: ch-git
spec:
  type: Git
  pathname: https://github.com/rokej/testrepo
