apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx-sub
spec:
  channel: dev/dev-helmrepo
  name: nginx-ingress
  placement:
    placementRef:
      kind: PlacementRule
      name: nginx-pr
  packageFilter:
    version: "1.36.3"
