apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx-sub
spec:
  channel: dev/dev-helmrepo
  name: ingress-nginx
  placement:
    placementRef:
      kind: PlacementRule
      name: nginx-pr
  packageOverrides:
  - packageName: ingress-nginx
    packageAlias: ingress-nginx-simple
    packageOverrides:
    - path: spec
      value:
        defaultBackend:
          enabled: true
          replicaCount: 3
