---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: multicluster-subscriber-metrics
  name: multicluster-subscriber-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      port: 8381
      protocol: TCP
      targetPort: 8381
  selector:
    component: application-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
