name: GoPostSubmit

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.19'
  GO_REQUIRED_MIN_VERSION: ''
  GOPATH: '/home/runner/work/multicloud-operators-subscription/multicloud-operators-subscription/go'
defaults:
  run:
    working-directory: go/src/github.com/open-cluster-management/multicloud-operators-subscription

jobs:
  images:
    name: images
    runs-on: ubuntu-latest
    if: ${{ github.repository.fork == false }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/github.com/open-cluster-management/multicloud-operators-subscription
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.1
      - name: images
        run: make build-images
      - name: push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push quay.io/open-cluster-management/multicloud-operators-subscription:latest
